services:
  current-date-a2a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: current-date-a2a
    ports:
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/.well-known/agent.json"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped